### ISSUE TITLE
Cannot install MinkowskiEngine with provided instructions

### ISSUE THREAD

**Issue by gholste** [facebookresearch/ConvNeXt-V2#63]
I have followed all instructions in `INSTALL.md`, and the provided command for installing the MinkowskiEngine does not work for me. Specifically, I ran every command exactly except for `git submodule update --init --recursive` and `git submodule update --recursive --remote`, which also do not work for me; instead, I ran ```sed -i "s/url.*/url=https:\/\/github.com\/shwoo93\/MinkowskiEngine.git/g" .gitmodules &&\
    git submodule update --init --recursive && git submodule update --recursive``` following https://github.com/facebookresearch/ConvNeXt-V2/issues/50.

After running `python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas`, I get the following error:
```WARNING: Skipping MinkowskiEngine as it is not installed.
--------------------------------
| CUDA compilation set         |
--------------------------------

Using BLAS=openblas
Using the default compiler
Traceback (most recent call last):
  File "setup.py", line 310, in <module>
    Extension(
  File "/home/gih5/miniconda3/envs/convnextv2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 867, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/gih5/miniconda3/envs/convnextv2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 975, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/gih5/miniconda3/envs/convnextv2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1982, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

These instructions seem incomplete to me. What am I supposed to set `CUDA_HOME` to? I am on a shared server and do not have sudo access or anything like `/usr/local/cuda-11.1`, which the MinkowskiEngine installation instructions suggest I should set `CUDA_HOME` to (https://github.com/shwoo93/MinkowskiEngine/tree/bbc30ef581ea6deb505976b663f5fc2358a83749); for example, the command `nvcc` is not found, but I can still access GPUs.

**Comment by gholste** [comment]
Update: If I separately install cuda-nvcc through conda (https://anaconda.org/nvidia/cuda-nvcc), I can see that `nvcc --version` works. I have tried setting `export CUDA_HOME=~/miniconda3/envs/convnextv2/bin/nvcc` (the output of `which nvcc`) and running `python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas`, but I still get this error:
```
--------------------------------
| CUDA compilation set         |
--------------------------------

Using BLAS=openblas
Using the default compiler
running install
/home/gih5/miniconda3/envs/convnextv2/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/gih5/miniconda3/envs/convnextv2/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiDepthwiseConvolution.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
creating build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
creating build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
running build_ext
error: [Errno 20] Not a directory: '/home/gih5/miniconda3/envs/convnextv2/bin/nvcc/bin/nvcc'
```

**Comment by braxtonowens** [comment]
I am also on a shared server and similarly fail at git `submodule update --init --recursive`

Just wanted to add pressure to this issue.

**Comment by uuhhuu** [comment]
Same problem

**Comment by benx13** [comment]
same
